#!/usr/bin/env bash
# quering server information with dig
# processed with awk

function query_subdomain() {
	s=$(dig "$2.$1" | grep -A1 "ANSWER" | tail -n 1);
	RTYPE=$(echo "$s" | awk '{print $4}');
	DEST=$(echo "$s" | awk '{print $5}');
        echo "The subdomain $2 is a $RTYPE record and points to $DEST}";
}

if [ $# -eq 1 ]
then
	for sub in www lb-01 web-01 web-02
	do
		query_subdomain "$1" "$sub";
	done
elif [ $# -eq 2 ]
then
	query_subdomain "$1" "$2";
fi
	
