#!/usr/bin/env bash
# copies a file to a webserver

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
fi

SOURCE=$1
IP=$2
USERNAME=$3

if [ $# -eq 3 ]
then
	scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$SOURCE" "$USERNAME@$IP:~/";
elif [ $# -gt 3 ]
then
	KEYFILE=$4
	scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$SOURCE" "$USERNAME@$IP:~/" -i "$KEYFILE";
fi
