#!/usr/bin/env bash
# installing an nginx server

sudo apt-get update;
sudo apt-get install nginx -y;
echo "Hello World!" > index.html && mv index.html /var/www/html/;

inputFile="/etc/nginx/sites-available/default";

sed -i "/location \/redirect_me {/,/\s}/d" "$inputFile";

redirect_string="\
	\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}";
sudo sed -i "/root \/var\/www\/html/i $redirect_string" "$inputFile";

sudo sed -i 's/tlocation/\tlocation/' "$inputFile";

sudo service nginx restart;
