#!/usr/bin/env bash
# creates a new server block and configures it

nginxFile=/etc/nginx/sites-available/default;

sudo apt-get update;
sudo apt-get install nginx -y;

# creates the webserver index page
sudo echo "Hello World!" > index.html && mv index.html /var/www/html/;

# creates the webserver error page
sudo echo "Ceci n'est pas une page" > error404.html && mv error404.html /var/www/html/;


# remove all custom header blocks and add a new one
sudo sed -i '/add_header/d' "$nginxFile";
sudo sed -i "/^\s*server_name _/a \\
        \n\tadd_header X-Served-By $HOSTNAME;" "$nginxFile";

sudo sed -i 's/tlocation/\tlocation/' "$nginxFile";

# restart nginx after editing conf
sudo service nginx restart;
