#!/usr/bin/env bash
# a script that demonstrate more use cases of signals in linux

function cleanup() {
	rm /var/run/myscript.pid;
	exit;
}

pgrep -f 100-process_and_pid_file > /var/run/myscript.pid;

trap 'echo "I hate the kill command"; cleanup' SIGTERM;

trap 'echo "Y U no love me?!"; cleanup' SIGINT;

while true
do
	echo "To infinity and beyond";
	sleep 2;
done

