#!/usr/bin/env bash
# script to demonstrate if statement in bash

count=0
maxCount=10

while [ $count -lt $maxCount ]
do
	echo "Best School";
	if [ $count -eq 8 ]
	then
		echo "Hi";
	fi
	(( count += 1 ));
done
