#!/usr/bin/env bash
# a script to demonstrate the use of if ... else
#+ statement in bash

count=1
max=10

while [ $count -le $max ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck";
	elif [ $count -eq 8 ]
	then
		echo "good luck";
	else
		echo "Best School";
	fi
	(( count += 1 ));
done
