#!/usr/bin/env bash
# script showing more advanced usage of while loop

hours=0
minutes=1

while [ $hours -le 12 ]
do
	echo "Hour: $hours";
	while [ $minutes -le 59 ]
	do
		echo "$minutes";
		(( minutes += 1 ));
	done
	(( minutes = 0 ));
	(( hours += 1 ));
done
