#!/usr/bin/env bash
# script demonstrating the use of cut command with the for loop

file_names=$(find . -type f -printf "%f\n" -not -path '*/.*' | cut -s -d "-" -f 2)

for file in $file_names
do
	echo "$file";
done
